### ISSUE TITLE
Trim spaces from spreadsheet keys

### ISSUE THREAD

**Issue by doup** [mobilejazz/Colloc#10]
We had this "error" where the spreadsheet had some spaces on the end of the key definition, resulting in something like this in our exported JSON file:
```
"my_key ": "translation"
       ^ please, no more
```

This led to untranslated content and confused developers.
It would be nice if the backend trimmed these spaces as part of the import/export process.

**Comment by joselufo** [comment]
Already working in progress in #11 

Asana task: https://app.asana.com/0/1202879294026954/1202994287335452/f
